CREATE TABLE IF NOT EXISTS "users" (
  "id" BIGSERIAL PRIMARY KEY,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "name" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "items" (
  "id" BIGSERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "available" BOOLEAN NOT NULL,
  "owner" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS "bookings" (
  "id" BIGSERIAL PRIMARY KEY,
  "item" BIGINT NOT NULL,
  "booker" BIGINT NOT NULL,
  "start" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  "end" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  "status" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "comments" (
  "id" BIGSERIAL PRIMARY KEY,
  "text" TEXT NOT NULL,
  "item" BIGINT NOT NULL,
  "author" BIGINT NOT NULL
);

ALTER TABLE "items" ADD FOREIGN KEY ("owner") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "bookings" ADD FOREIGN KEY ("booker") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "bookings" ADD FOREIGN KEY ("item") REFERENCES "items" ("id") ON DELETE CASCADE;

ALTER TABLE "comments" ADD FOREIGN KEY ("item") REFERENCES "items" ("id") ON DELETE CASCADE;

ALTER TABLE "comments" ADD FOREIGN KEY ("author") REFERENCES "users" ("id") ON DELETE CASCADE;
